### ISSUE TITLE
 Error: The GCM API Key should be a non-emtpy string, (start-server)

### ISSUE THREAD

**Issue by mauricionr** [mozilla/serviceworker-cookbook#242]
I was trying to run `npm run watch` and i got this error

```logs
[21:35:05] Starting 'start-server'...
[21:35:05] 'start-server' errored after 347 ms
[21:35:05] Error: The GCM API Key should be a non-emtpy string.
    at Object.setGCMAPIKey (/mnt/c/Users/Mauricio Nunes dos R/Documents/Git/serviceworker-cookbook/node_modules/web-push/index.js:96:11)
    at Object.<anonymous> (/mnt/c/Users/Mauricio Nunes dos R/Documents/Git/serviceworker-cookbook/push-clients/server.js:7:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireRecipe (/mnt/c/Users/Mauricio Nunes dos R/Documents/Git/serviceworker-cookbook/server.js:71:3)
    at Array.map (native)

```

**Comment by zhengqingxin** [comment]
I met this too,how to resolve this?

**Comment by marco-c** [comment]
Set the GCM_API_KEY env variable to your GCM API key.
It also works if you set it to a dummy API key.

```sh
GCM_API_KEY=something npm run watch
```
