### ISSUE TITLE
Cannot start the server locally

### ISSUE THREAD

**Issue by upsuper** [mozilla/serviceworker-cookbook#243]
I ran `npm install` and `gulp watch`, I got the following message:
```
[17:31:29] Using gulpfile ~/serviceworker-cookbook/gulpfile.js
[17:31:29] Starting 'clean'...
[17:31:29] Starting 'lint'...
[17:31:29] Finished 'clean' after 201 ms
[17:31:29] Starting 'build:index'...
[17:31:29] Starting 'build:categories'...
[17:31:29] Starting 'build:intros'...
[17:31:29] Starting 'build:demos'...
[17:31:29] Starting 'build:recipes'...
[17:31:29] Starting 'build:docs'...
[17:31:29] Starting 'build:css'...
[17:31:29] Starting 'build:js'...
[17:31:29] Starting 'build:tabzilla'...
[17:31:29] Starting 'build:favicon'...
[17:31:30] Finished 'build:index' after 431 ms
[17:31:30] Finished 'build:categories' after 429 ms
[17:31:30] Finished 'build:intros' after 429 ms
[17:31:30] Finished 'build:demos' after 429 ms
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at Backend.process (~/serviceworker-cookbook/node_modules/gulp-docco/lib/backend.js:46:52)
    at Transform.<anonymous> (~/serviceworker-cookbook/node_modules/gulp-docco/index.js:70:14)
    at Transform.<anonymous> (~/serviceworker-cookbook/node_modules/gulp-docco/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Transform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Transform.emit (events.js:185:7)
    at finishMaybe (~/serviceworker-cookbook/node_modules/gulp-docco/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (~/serviceworker-cookbook/node_modules/gulp-docco/node_modules/readable-stream/lib/_stream_writable.js:378:3)
```

**Comment by ejulen** [comment]
I had the same issue on Node 6. After switching to Node 4 the issue went away.

**Comment by delapuente** [comment]
Indeed, you need up to Node 4.2.4

**Comment by upsuper** [comment]
You should probably add that requirement to README or somewhere obvious. Also, it would be helpful to add some guides about how to install Node 4 in different platforms. It doesn't seem easy nowadays.

**Comment by upsuper** [comment]
Without those info, this repo would definitely be considered not welcome to new contributions, since it is pretty hard for people to start hacking. Previous contributors may also find it hard to continue contributing after their local node gets upgraded.

**Comment by marco-c** [comment]
Can you file a new issue to make the cookbook compatible with Node.js?
